# -*- coding: utf-8 -*-
"""startup expansion in use project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fX1AkBhPOiQfOxTgkuTzZI32NfMzGrh0
"""

#                                              Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#                                              Importing Dataset

startup_data = pd.read_excel("/content/startup-expansion.xlsx")
startup_data

#                                            preprocessing Data

startup_data.info()

startup_data[['Marketing Spend','Revenue']].describe().round(2)

startup_data.isna().sum()

startup_data.duplicated().sum()

startup_data['City'].unique()

startup_data['City'].value_counts()

startup_data['State'].unique()

startup_data['State'].value_counts()

#                                            Exploring & Analysing Data

startup_data.sample(10)

startup_data['New Expansion'].value_counts().plot.bar()

startup_data[startup_data['New Expansion']=='Old'].groupby('State').sum()['Revenue'].nlargest(10)

startup_data[startup_data['New Expansion']=='New'].groupby('State').sum()['Revenue'].nlargest(10)

startup_data['profit']=startup_data['Revenue']-startup_data['Marketing Spend']
startup_data

#   Profitability Ratio = (profit / cost)
startup_data['PrRa%'] = round((startup_data['profit']/startup_data['Marketing Spend']),2)
startup_data

startup_data.to_csv('startup_expansion_modifid.csv')

